package vieww;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CadastroL;
import model.ProdutoDAO;

public class Listagem extends javax.swing.JFrame {

    /**
     * Creates new form FilmeListagem
     */
    public Listagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bTnATUALIZAR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TabelaScroll = new javax.swing.JScrollPane();
        tabelaa = new javax.swing.JTable();
        bTnNOVO = new javax.swing.JButton();
        bTnEXCLUIR = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PesquisarCampo = new javax.swing.JTextField();
        bTnBUSCAR = new javax.swing.JButton();

        bTnATUALIZAR.setText("Atualizar");
        bTnATUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTnATUALIZARActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelaScroll.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelaa.setModel(montarTabela());
        tabelaa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelaaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TabelaScroll.setViewportView(tabelaa);

        bTnNOVO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bTnNOVO.setForeground(new java.awt.Color(0, 204, 0));
        bTnNOVO.setText("+Novo ");
        bTnNOVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTnNOVOActionPerformed(evt);
            }
        });

        bTnEXCLUIR.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bTnEXCLUIR.setForeground(new java.awt.Color(255, 51, 51));
        bTnEXCLUIR.setText("Excluir");
        bTnEXCLUIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTnEXCLUIRActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Listagem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Lista de Cadastro dos produtos");

        PesquisarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarCampoActionPerformed(evt);
            }
        });

        bTnBUSCAR.setText("Buscar");
        bTnBUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTnBUSCARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bTnNOVO)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bTnEXCLUIR)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bTnBUSCAR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PesquisarCampo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 1, Short.MAX_VALUE)
                                        .addComponent(TabelaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTnBUSCAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TabelaScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTnEXCLUIR, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTnNOVO))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTnNOVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTnNOVOActionPerformed
        cadastroVIEW pl = new cadastroVIEW();
        pl.setVisible(true);
    }//GEN-LAST:event_bTnNOVOActionPerformed

    private void bTnEXCLUIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTnEXCLUIRActionPerformed
        int id = getPosicao();

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse registro? ");
        if (resposta == 0) {
            ProdutoDAO.excluir(id);
        }
        //Para reexibir e atualizar a tabela na mesma tela
        tabelaa.setModel(montarTabela());
        TabelaScroll.setViewportView(tabelaa);
    }//GEN-LAST:event_bTnEXCLUIRActionPerformed

    private void bTnATUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTnATUALIZARActionPerformed
        cadastroVIEW pl = new cadastroVIEW();
        pl.setVisible(true);
    }//GEN-LAST:event_bTnATUALIZARActionPerformed

    private void tabelaaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaaAncestorAdded

    private void PesquisarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarCampoActionPerformed

    }//GEN-LAST:event_PesquisarCampoActionPerformed

    private void bTnBUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTnBUSCARActionPerformed

    }//GEN-LAST:event_bTnBUSCARActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listagem().setVisible(true);
            }
        });
    }

    private DefaultTableModel montarTabela() {
        String[] colunas = {"id", "Nome", "Data", "Situação"};

        // Criamos a tabela
        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);

        List<CadastroL> lista = ProdutoDAO.listarTodos();

        for (int i = 0; i < lista.size(); i++) {
            CadastroL p = lista.get(i);

            String[] linha = {
                Integer.toString(p.getId()),
                p.getNome(),
                CadastroL.converterParaJava(p.getDataa()),
                p.getSituacao()
            };

            tabela.addRow(linha);

        }

        tabela.fireTableDataChanged();

        return tabela;
    }

    private int getPosicao() {
        int posicao = tabelaa.getSelectedRow();
        if (posicao <= -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir.");
        }
        return Integer.parseInt((String) tabelaa.getValueAt(posicao, 0));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PesquisarCampo;
    private javax.swing.JScrollPane TabelaScroll;
    private javax.swing.JButton bTnATUALIZAR;
    private javax.swing.JButton bTnBUSCAR;
    private javax.swing.JButton bTnEXCLUIR;
    private javax.swing.JButton bTnNOVO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tabelaa;
    // End of variables declaration//GEN-END:variables
}
